export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const PARTNERSHIPS_GET_SUCCESS = "PARTNERSHIPS_GET_SUCCESS";
export const PARTNERSHIPS_GET_REQUEST = "PARTNERSHIPS_GET_REQUEST";
export const PARTNERSHIP_CREATE_CUSTOMER_REQUEST =
  "PARTNERSHIPS_CREATE_CUSTOMER_REQUEST";
export const PARTNERSHIP_CREATE_CUSTOMER_SUCCESS =
  "PARTNERSHIPS_CREATE_CUSTOMER_SUCCESS";
export const PARTNERSHIP_SUBSCRIBE_REQUEST = "PARTNERSHIPS_SUBSCRIBE_REQUEST";
export const PARTNERSHIP_SUBSCRIBE_SUCCESS = "PARTNERSHIPS_SUBSCRIBE_SUCCESS";
export const PARTNERSHIP_TRANSACTION_SUCCESS =
  "PARTNERSHIP_TRANSACTION_SUCCESS";
export const PARTNERSHIP_CANCEL_SUBSCRIBE_REQUEST =
  "PARTNERSHIPS_CANCEL_SUBSCRIBE_REQUEST";
export const PARTNERSHIP_CANCEL_SUBSCRIBE_SUCCESS =
  "PARTNERSHIPS_CANCEL_SUBSCRIBE_SUCCESS";