export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";

export const USER_ACTIVITY_REQUEST = "USER_ACTIVITY_REQUEST";
export const USER_ACTIVITY_SUCCESS = "USER_ACTIVITY_SUCCESS";

export const USER_UPDATE_INFO_REQUEST = "USER_UPDATE_INFO_REQUEST";
export const USER_UPDATE_INFO_SUCCESS = "USER_UPDATE_INFO_SUCCESS";

export const USERINFO_GET_SUCCESS = "USERINFO_GET_SUCCESS";
export const USERINFO_GET_REQUEST = "USERINFO_GET_REQUEST";

export const USERPOLL_GET_SUCCESS = "USERPOLL_GET_SUCCESS";

export const ABOUT_CHANGE_SUCCESS = "ABOUT_CHANGE_SUCCESS";

export const SOCIAL_CHANGE_SUCCESS = "SOCIAL_CHANGE_SUCCESS";

export const NOTIFICATION_CHANGE_SUCCESS = "NOTIFICATION_CHANGE_SUCCESS";

export const USER_AVATAR_UPLOAD_SUCCESS = "USER_AVATAR_UPLOAD_SUCCESS";

export const THINK_POST_REQUEST = "THINK_POST_REQUEST";
export const THINK_POST_SUCCESS = "THINK_POST_SUCCESS";

export const HEADER_GET_SUCCESS = "HEADER_GET_SUCCESS";
export const POST_FOLLOWER_SUCCESS = "POST_FOLLOWER_SUCCESS";

export const GET_FOLLOWERS_LIST_SUCCESS = "GET_FOLLOWERS_LIST_SUCCESS";
export const UN_FRIEND_SUCCESS = "UN_FRIEND_SUCCESS";

export const GET_SHOOT_OUT_SUCCESS = "GET_SHOOT_OUT_SUCCESS";
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS";
export const GET_ALL_PHOTOS_SUCCESS = "GET_ALL_PHOTOS_SUCCESS";
