export const LOCATION_QUICK_ARRIVAL_REQUEST = "LOCATION_QUICK_ARRIVAL_REQUEST";
export const LOCATION_QUICK_ARRIVAL_SUCCESS = "LOCATION_QUICK_ARRIVAL_SUCCESS";

export const LOCATION_QUICK_DEPARTURE_REQUEST =
  "LOCATION_QUICK_DEPARTURE_REQUEST";
export const LOCATION_QUICK_DEPARTURE_SUCCESS =
  "LOCATION_QUICK_DEPARTURE_SUCCESS";

export const USER_LOCATION_REQUEST = "USER_LOCATION_REQUEST";
export const USER_LOCATION_ID_SUCCESS = "USER_LOCATION_ID_SUCCESS";

export const USER_EXPIRED_ARRIVAL_REQUEST = "USER_EXPIRED_ARRIVAL_REQUEST";
export const USER_EXPIRED_ARRIVAL_SUCCESS = "USER_EXPIRED_ARRIVAL_SUCCESS";

export const LOCATION_FAVORITE_REQUEST = "LOCATION_FAVORITE_REQUEST";
export const LOCATION_FAVORITE_SUCCESS = "LOCATION_FAVORITE_SUCCESS";


