export const LOCATION_QUICK_ARRIVAL_REQUEST = "LOCATION_QUICK_ARRIVAL_REQUEST";
export const LOCATION_QUICK_ARRIVAL_SUCCESS = "LOCATION_QUICK_ARRIVAL_SUCCESS";

export const LOCATION_QUICK_DEPARTURE_REQUEST =
  "LOCATION_QUICK_DEPARTURE_REQUEST";
export const LOCATION_QUICK_DEPARTURE_SUCCESS =
  "LOCATION_QUICK_DEPARTURE_SUCCESS";

export const USER_LOCATION_REQUEST = "USER_LOCATION_REQUEST";
export const USER_LOCATION_SUCCESS = "USER_LOCATION_SUCCESS";
