export const LOCATION_QUICK_ARRIVAL_REQUEST = "LOCATION_QUICK_ARRIVAL_REQUEST";
export const LOCATION_QUICK_ARRIVAL_SUCCESS = "LOCATION_QUICK_ARRIVAL_SUCCESS";

export const LOCATION_QUICK_DEPARTURE_REQUEST =
  "LOCATION_QUICK_DEPARTURE_REQUEST";
export const LOCATION_QUICK_DEPARTURE_SUCCESS =
  "LOCATION_QUICK_DEPARTURE_SUCCESS";

export const USER_LOCATION_REQUEST = "USER_LOCATION_REQUEST";
export const USER_LOCATION_SUCCESS = "USER_LOCATION_SUCCESS";
export const USER_LOCATION_ADD_SUCCESS = "USER_LOCATION_ADD_SUCCESS";
export const USER_LOCATION_ID_SUCCESS = "USER_LOCATION_ID_SUCCESS";

export const LOCATION_REVIEW_REQUEST = "LOCATION_REVIEW_REQUEST";
export const LOCATION_REVIEW_SUCCESS = "LOCATION_REVIEW_SUCCESS";

export const LOCATION_UPDATE_REQUEST = "LOCATION_UPDATE_REQUEST";
export const LOCATION_UPDATE_SUCCESS = "LOCATION_UPDATE_SUCCESS";

export const LOCATION_DELETE_REQUEST = "LOCATION_DELETE_REQUEST";
export const LOCATION_DELETE_SUCCESS = "LOCATION_DELETE_SUCCESS";

export const LOCATION_FAVORITE_REQUEST = "LOCATION_FAVORITE_REQUEST";
export const LOCATION_FAVORITE_SUCCESS = "LOCATION_FAVORITE_SUCCESS";
export const GET_ALL_ACTIVE_LOCATIONs_SUCCESS
= "GET_ALL_ACTIVE_LOCATIONs_SUCCESS";
export const LOCATION_GET_FAVORITE_REQUEST = "LOCATION_GET_FAVORITE_REQUEST";
export const LOCATION_GET_FAVORITE_SUCCESS = "LOCATION_GET_FAVORITE_SUCCESS";
