export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_EMAIL_VERIFICATION_REQUEST =
  " USER_EMAIL_VERIFICATION_REQUEST";
export const USER_EMAIL_VERIFICATION_SUCCESS =
  " USER_EMAIL_VERIFICATION_SUCCESS";

export const SUB_CATEGORY_GET_SUCCESS = "SUB_CATEGORY_GET_SUCCESS";
export const ALL_SUB_CATEGORY_GET_SUCCESS = "ALL_SUB_CATEGORY_GET_SUCCESS";
export const GET_MYFOLLOWER_SUCCESS = "GET_MYFOLLOWER_SUCCESS";
export const GET_FOLLOW_AND_FOLLOWING_SUCCESS =
  "GET_FOLLOW_AND_FOLLOWING_SUCCESS";

export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_REQUEST = "GET_NOTIFICATION_REQUEST";

export const CLEAR_NOTIFICATION_SUCCESS = "CLEAR_NOTIFICATION_SUCCESS";
export const CLEAR_NOTIFICATION_REQUEST = "CLEAR_NOTIFICATION_REQUEST";

export const UPDATE_NOTIFICATION_REQUEST = "UPDATE_NOTIFICATION_REQUEST";
export const UPDATE_NOTIFICATION_SUCCESS = "UPDATE_NOTIFICATION_SUCCESS";

export const SETTINGS_VALUE_GET_SUCCESS = "SETTINGS_VALUE_GET_SUCCESS";

export const SETTINGS_VALUE_GET_REQUEST = "SETTINGS_VALUE_GET_REQUEST";
export const PARNTER_SETTINGS_CHANGE = "PARTNER_SETTINGS_CHANGE";

export const GET_FAQ_SUCCESS = "GET_FAQ_SUCCESS";

export const BUSINESS_UPDATE_INFO_REQUEST = "BUSINESS_UPDATE_INFO_REQUEST";
export const BUSINESS_UPDATE_INFO_SUCCESS = "BUSINESS_UPDATE_INFO_SUCCESS";

export const GET_DEFAULT_AVATAR_REQUEST = "GET_DEFAULT_AVATAR_REQUEST";
export const GET_DEFAULT_AVATAR_SUCCESS = "GET_DEFAULT_AVATAR_SUCCESS";

export const LOGOUT = "LOGOUT";
