export const MAIL_COMPOSE_REQUEST = "MAIL_COMPOSE_REQUEST";
export const MAIL_COMPOSE_SUCCESS = "MAIL_COMPOSE_SUCCESS";

export const SENT_INVITE_REQUEST = "SENT_INVITE_REQUEST";
export const SENT_INVITE_SUCCESS = "SENT_INVITE_SUCCESS";

export const GET_INBOX_REQUEST = "GET_INBOX_REQUEST";
export const GET_INBOX_SUCCESS = "GET_INBOX_SUCCESS";

export const GET_SENT_REQUEST = "GET_SENT_REQUEST";
export const GET_SENT_SUCCESS = "GET_SENT_SUCCESS";

export const DELETE_SENT_REQUEST = "DELETE_SENT_REQUEST";
export const DELETE_SENT_SUCCESS = "DELETE_SENT_SUCCESS";

export const DELETE_INBOX_REQUEST = "DELETE_INBOX_REQUEST";
export const DELETE_INBOX_SUCCESS = "DELETE_INBOX_SUCCESS";
export const DOWNLOAD_FILE_SUCCESS = "DOWNLOAD_FILE_SUCCESS";
export const RESEND_INVITE_SUCCESS = "RESEND_INVITE_SUCCESS";

export const GET_PENDING_REQUEST = "GET_PENDING_REQUEST";
export const GET_PENDING_SUCCESS = "GET_PENDING_SUCCESS";

export const GET_NOTICE_REQUEST = "GET_NOTICE_REQUEST";
export const GET_NOTICE_SUCCESS = "GET_NOTICE_SUCCESS";

export const UPDATE_MAIL_REQUEST = "UPDATE_MAIL_REQUEST";
export const UPDATE_MAIL_SUCCESS = "UPDATE_MAIL_SUCCESS";

export const DELETE_MAIL_REQUEST = "DELETE_MAIL_REQUEST";
export const DELETE_MAIL_SUCCESS = "DELETE_MAIL_SUCCESS";

export const BULK_MAIL_ACTION_REQUEST = "BULK_MAIL_ACTION_REQUEST";
export const BULK_MAIL_ACTION_SUCCESS = "BULK_MAIL_ACTION_SUCCESS";

export const GET_ISREAD_REQUEST = "GET_ISREAD_REQUEST";
export const GET_ISREAD_SUCCESS = "GET_ISREAD_SUCCESS";
