export const MAIL_COMPOSE_REQUEST = 'MAIL_COMPOSE_REQUEST';
export const MAIL_COMPOSE_SUCCESS = 'MAIL_COMPOSE_SUCCESS';
export const SENT_INVITE_REQUEST = 'SENT_INVITE_REQUEST';
export const SENT_INVITE_SUCCESS = 'SENT_INVITE_SUCCESS';

