export const MAIL_COMPOSE_REQUEST = 'MAIL_COMPOSE_REQUEST';
export const MAIL_COMPOSE_SUCCESS = 'MAIL_COMPOSE_SUCCESS';

export const SENT_INVITE_REQUEST = 'SENT_INVITE_REQUEST';
export const SENT_INVITE_SUCCESS = 'SENT_INVITE_SUCCESS';

export const GET_INBOX_REQUEST = 'GET_INBOX_REQUEST';
export const GET_INBOX_SUCCESS = 'GET_INBOX_SUCCESS';

export const GET_SENT_REQUEST = 'GET_SENT_REQUEST';
export const GET_SENT_SUCCESS = 'GET_SENT_SUCCESS';

export const DELETE_SENT_REQUEST = 'DELETE_SENT_REQUEST';
export const DELETE_SENT_SUCCESS = 'DELETE_SENT_SUCCESS';

export const DELETE_INBOX_REQUEST = 'DELETE_INBOX_REQUEST';
export const DELETE_INBOX_SUCCESS = 'DELETE_INBOX_SUCCESS';


